name: appproduits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  drift_flutter: ^0.2.1
  sqlite3: ^2.4.7
  ffi: ^2.1.3
  cupertino_icons: ^1.0.6


  firebase_ui_auth: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
