// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
     apiKey: "AIzaSyD8JpkouX7CZ2F_R3OhXkdShireg6np4RQ",
  authDomain: "atelier-4-n-benzala-iir5-fa98a.firebaseapp.com",
  projectId: "atelier-4-n-benzala-iir5-fa98a",
  storageBucket: "atelier-4-n-benzala-iir5-fa98a.firebasestorage.app",
  messagingSenderId: "426511571683",
  appId: "1:426511571683:web:2764f9ca07624f83aa43d6"
 );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-Lg_wkdWXcW3AuBzJOaMZxyfqpNfFm8',
    appId: '1:426511571683:android:7549abd374d79102aa43d6',
    messagingSenderId: '426511571683',
    projectId: 'atelier-4-n-benzala-iir5-fa98a',
    storageBucket: 'atelier-4-n-benzala-iir5-fa98a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkXChCih3NDAcet3I7dTR0SGhm3VeYIU',
    appId: '1:426511571683:ios:690ee9e6f59b1f8daa43d6',
    messagingSenderId: '426511571683',
    projectId: 'atelier-4-n-benzala-iir5-fa98a',
    storageBucket: 'atelier-4-n-benzala-iir5-fa98a.firebasestorage.app',
    iosBundleId: 'com.example.appproduits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYkXChCih3NDAcet3I7dTR0SGhm3VeYIU',
    appId: '1:426511571683:ios:690ee9e6f59b1f8daa43d6',
    messagingSenderId: '426511571683',
    projectId: 'atelier-4-n-benzala-iir5-fa98a',
    storageBucket: 'atelier-4-n-benzala-iir5-fa98a.firebasestorage.app',
    iosBundleId: 'com.example.appproduits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8JpkouX7CZ2F_R3OhXkdShireg6np4RQ',
    appId: '1:426511571683:web:7a76fdc8dc65673caa43d6',
    messagingSenderId: '426511571683',
    projectId: 'atelier-4-n-benzala-iir5-fa98a',
    authDomain: 'atelier-4-n-benzala-iir5-fa98a.firebaseapp.com',
    storageBucket: 'atelier-4-n-benzala-iir5-fa98a.firebasestorage.app',
  );
}
